OmokNoonE/PPM-backend

src/main/java/org/omoknoone/ppm/domain/employee/aggregate/Employee.java, src/main/java/org/omoknoone/ppm/domain/employee/controller/EmployeeController.java, src/main/java/org/omoknoone/ppm/domain/employee/dto/ModifyEmployeeRequestDTO.java, src/main/java/org/omoknoone/ppm/domain/employee/dto/ViewEmployeeResponseDTO.java, src/main/java/org/omoknoone/ppm/domain/employee/repository/EmployeeRepository.java, src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeService.java, src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceImpl.java, src/test/java/org/omoknoone/ppm/domain/employee/controller/EmployeeControllerTests.java, src/test/java/org/omoknoone/ppm/domain/employee/dto/ViewEmployeeResponseDTOTest.java
> #51 회원 관련 기능 개발
> 회원 정보 수정, 조회 기능 개발
테스트 코드는 추후 수정
=> [PR] 회원 조회 및 수정 기능 개발

src/main/java/org/omoknoone/ppm/common/exception/GlobalExceptionHandler.java, src/main/java/org/omoknoone/ppm/commoncode/aggregate/CommonCode.java, src/main/java/org/omoknoone/ppm/commoncode/dto/CommonCodeGroupResponseDTO.java, src/main/java/org/omoknoone/ppm/commoncode/dto/CommonCodeResponseDTO.java, src/main/java/org/omoknoone/ppm/commoncode/repository/CommonCodeRepository.java, src/main/java/org/omoknoone/ppm/commoncode/service/CommonCodeService.java, src/main/java/org/omoknoone/ppm/commoncode/service/CommonCodeServiceImpl.java, src/main/resources/messages.yml
>  #52 
> 공통 코드 그룹 코드에서 발생할 수 있는 예외 처리를 위한 코드가 추가 되었습니다. globalExceptionHandler를 활용 하여 예외 처리에 대한 메시지가 한글로 출력됩니다.
🫡
> acfb595 commit에 실제 예외 처리를 위한 코드가 구현 되어 있습니다.
=> [PR] 공통 코드 관리 기능 코드 수정 및 예외 처리 코드 추가

src/main/java/org/omoknoone/ppm/PpmApplication.java, src/main/java/org/omoknoone/ppm/domain/employee/aggregate/Auth.java, src/main/java/org/omoknoone/ppm/domain/employee/controller/AuthController.java, src/main/java/org/omoknoone/ppm/domain/employee/dto/LoginEmployeeDTO.java, src/main/java/org/omoknoone/ppm/domain/employee/dto/RequestLoginDTO.java, src/main/java/org/omoknoone/ppm/domain/employee/repository/AuthRepository.java, src/main/java/org/omoknoone/ppm/domain/employee/service/AuthService.java, src/main/java/org/omoknoone/ppm/domain/employee/service/AuthServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeService.java, src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceImpl.java, src/main/java/org/omoknoone/ppm/security/AuthenticationFilter.java, src/main/java/org/omoknoone/ppm/security/CorsConfig.java, src/main/java/org/omoknoone/ppm/security/JwtFilter.java, src/main/java/org/omoknoone/ppm/security/JwtTokenProvider.java, src/main/java/org/omoknoone/ppm/security/JwtUtil.java, src/main/java/org/omoknoone/ppm/security/Role.java, src/main/java/org/omoknoone/ppm/security/SessionEmployee.java, src/main/java/org/omoknoone/ppm/security/WebSecurity.java
#17 로그인 기능 개발
#18 로그아웃 기능 개발
> **Spring Security를 적용하여 로그인, 로그아웃 기능 개발**
- 사원번호와 비밀번호를 입력받아 DB에 있는 암호화된 비밀번호와 검증하여 성공 시 로그인
- 로그인 성공 시, JWT 토큰 발급하여 Access Token은 header로 Refresh Token은 Cookie에 담아 응답
- Refresh Token은 mariaDB에 저장, 이전 프로젝트에서는 Redis를 사용했으나 적은 사용자를 위해 AWS ElastiCache를 도입을 하는 것보다는 사용 예정인 RDS에 mariaDB를 사용하는 것이 좋을 것으로 판단되어 RDB에 저장하기로 결정
- Refresh Token을 파기하여 로그아웃으로 전환
- 역할(Role)은 만들어 놓았으나 다른 기능 개발이 종료 된 이후에 역할에 맞춰 메소드 권한 부여할 예정
=> [PR] 회원 로그인 및 로그아웃 기능 개발

src/main/java/org/omoknoone/ppm/domain/employee/aggregate/Employee.java, src/main/java/org/omoknoone/ppm/domain/employee/controller/EmployeeController.java, src/main/java/org/omoknoone/ppm/domain/employee/dto/SignUpEmployeeRequestDTO.java, src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeService.java, src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceImpl.java
> #51 회원 관련 기능 개발
> 비밀번호 암호화를 위해 기능 개발, 기존에는 인사팀에서 가입 시켜준다는 가정하에 개발하지 않았는데 비밀번호 암호화를 위해 API 개발하였음
=> [PR] 회원가입 기능 개발

src/main/java/org/omoknoone/ppm/domain/employee/aggregate/Auth.java, src/main/java/org/omoknoone/ppm/domain/employee/controller/AuthController.java, src/main/java/org/omoknoone/ppm/domain/employee/repository/AuthRepository.java, src/main/java/org/omoknoone/ppm/domain/employee/service/AuthService.java, src/main/java/org/omoknoone/ppm/domain/employee/service/AuthServiceImpl.java, src/main/java/org/omoknoone/ppm/security/AuthenticationFilter.java, src/main/java/org/omoknoone/ppm/security/JwtFilter.java, src/main/java/org/omoknoone/ppm/security/JwtUtil.java
> #17 로그인 기능 개발, #18 로그아웃 기능 개발
> Token PK에 UUID(랜덤한 식별자)를 사용하여 토큰 보안 강화
> [PR] #61 먼저 코드리뷰와 merge 부탁드립니다.
=> [PR] 토큰 PK 자료형을 UUID로 변경

src/main/java/org/omoknoone/ppm/domain/project/aggregate/Project.java, src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectController.java, src/main/java/org/omoknoone/ppm/domain/project/dto/CreateProjectRequestDTO.java, src/main/java/org/omoknoone/ppm/domain/project/dto/ModifyProjectRequestDTO.java, src/main/java/org/omoknoone/ppm/domain/project/repository/ProjectRepository.java, src/main/java/org/omoknoone/ppm/domain/project/service/ProjectService.java, src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
> #21 프로젝트 임시 생성 기능 개발, #22 프로젝트 착수 전환 기능 개발
> 프로젝트 생성 시 상태 값이 임시로 생성되게 개발
> 착수 상태로 전환 기능 개발 (권한 변경되는 부분은 추후에 기능 개발 다 끝나고 추가할 예정)
=> [PR] 프로젝트 생성, 수정 기능 개발

src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMember.java, src/main/java/org/omoknoone/ppm/domain/projectmember/controller/ProjectMemberController.java, src/main/java/org/omoknoone/ppm/domain/projectmember/dto/CreateProjectMemberRequestDTO.java, src/main/java/org/omoknoone/ppm/domain/projectmember/dto/CreateProjectMemberResponseDTO.java, src/main/java/org/omoknoone/ppm/domain/projectmember/dto/ModifyProjectMemberRequestDTO.java, src/main/java/org/omoknoone/ppm/domain/projectmember/dto/viewProjectMembersByProjectResponseDTO.java, src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java, src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java, src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java
> #14
> 프로젝트에 포함 되어 있는 구성원 목록을 조회 할 수 있는 기능 개발 (프로젝트, 역할 엔티티가 완성 된 후에 테스트가 진행 될 예정)
> 24ff81f a91e192 commit에 서비스와 컨트롤러 코드가 구현 되어 있습니다.
=> [PR] 프로젝트 구성원 조회 관리 기능 개발

src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleHistoryService.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/task/aggregate/Task.java, src/main/java/org/omoknoone/ppm/domain/task/controller/TaskController.java, src/main/java/org/omoknoone/ppm/domain/task/dto/CreateTaskDTO.java, src/main/java/org/omoknoone/ppm/domain/task/dto/ModifyTaskDTO.java, src/main/java/org/omoknoone/ppm/domain/task/dto/RequestCreateTaskDTO.java, src/main/java/org/omoknoone/ppm/domain/task/dto/RequestModifyTaskDTO.java, src/main/java/org/omoknoone/ppm/domain/task/dto/TaskDTO.java, src/main/java/org/omoknoone/ppm/domain/task/repository/TaskRepository.java, src/main/java/org/omoknoone/ppm/domain/task/service/TaskService.java, src/main/java/org/omoknoone/ppm/domain/task/service/TaskServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/task/vo/ResponseTask.java
#49 
- 업무 등록
- 업무 수정
- 업무 삭제
- 업무 상세 조회
- 일정에 따른 업무 조회
- 사전에 작성한 일정에서 작성 실수한 부분 수정 및 TODO도 같이 포함되어 있습니다.
=> [PR] 업무 기능 구현

src/main/java/org/omoknoone/ppm/domain/stakeholders/aggregate/Stakeholders.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/controller/StakeholdersController.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/dto/CreateStakeholdersDTO.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/dto/ModifyStakeholdersDTO.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/dto/RequestCreateStakeholdersDTO.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/dto/RequestModifyStakeholdersDTO.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/dto/StakeholdersDTO.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/repository/StakeholdersRepository.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersService.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/vo/ResponseStakeholders.java
#46
- 이해관계자 등록
- 이해관계자 수정 (type, project_member_id)
- 이해관계자 제외
- 일정에 따른 이해관계자 조회
>
=> [PR] 이해관계자 기능 구현

src/main/java/org/omoknoone/ppm/domain/plpermission/controller/PLPermissionController.java, src/main/java/org/omoknoone/ppm/domain/plpermission/dto/CreatePLPermissionDTO.java, src/main/java/org/omoknoone/ppm/domain/plpermission/dto/PLPermissionDTO.java, src/main/java/org/omoknoone/ppm/domain/plpermission/dto/RequestCreatePLPermissionDTO.java, src/main/java/org/omoknoone/ppm/domain/plpermission/repository/PLPermissionRepository.java, src/main/java/org/omoknoone/ppm/domain/plpermission/service/PLPermissionService.java, src/main/java/org/omoknoone/ppm/domain/plpermission/service/PLPermissionServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/plpermission/vo/ResponsePLPermission.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/aggregate/Stakeholders.java
#46
- PL 권한 등록
- PL 권한 삭제
- 구성원 ID에 따른 PL 권한 조회
- 일정에 따른 PL 권한 조회
>
=>  [PR] PL 권한 기능 구현

src/main/java/org/omoknoone/ppm/domain/requirements/aggregate/Requirements.java, src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsController.java, src/main/java/org/omoknoone/ppm/domain/requirements/dto/RequirementsDTO.java, src/main/java/org/omoknoone/ppm/domain/requirements/repository/RequirementsRepository.java, src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsService.java, src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/requirements/vo/RequestModifyRequirement.java, src/main/java/org/omoknoone/ppm/domain/requirements/vo/RequestRequirement.java, src/main/java/org/omoknoone/ppm/domain/requirements/vo/ResponseRequirement.java
요구사항 등록, 수정, softdelete 기능 개발
> 
- 요구사항 등록 기능
- 요구사항 수정 기능
- 요구사항 삭제 기능(soft delete)
> 확인해주신 이후 코멘트 참고해서 수정할 부분이 있다면 수정하도록 하겠습니다.
=> [PR]요구사항 등록, 수정, 삭제(soft delete) 기능 구현

src/main/java/org/omoknoone/ppm/domain/requirements/aggregate/Requirements.java, src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsController.java, src/main/java/org/omoknoone/ppm/domain/requirements/dto/RequirementsDTO.java, src/main/java/org/omoknoone/ppm/domain/requirements/dto/RequirementsListByProjectDTO.java, src/main/java/org/omoknoone/ppm/domain/requirements/repository/RequirementsRepository.java, src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsService.java, src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/requirements/vo/ResponseRequirementsListByProject.java
>- #81 
- projectId를 통한 requirementsList 조회
- projectId, requirementsId를 통한 requirement 조회
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요.
=> [PR]프로젝트 ID를 통한 요구사항 목록 조회, 프로젝트 ID 및 요구사항 ID를 통한 요구사항 조회 기능

src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleController.java, src/main/java/org/omoknoone/ppm/domain/schedule/dto/SearchScheduleListDTO.java, src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRepository.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/schedule/vo/ResponseSearchScheduleList.java
> - #35 
>
- ScheduleTitle을 통한 일정 검색 기능 구현
=> [PR] ScheduleTitle을 통한 일정 검색 기능 구현

src/main/java/org/omoknoone/ppm/domain/projectDashboard/controller/GraphController.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsController.java, src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/schedule/dto/UpdateDataDTO.java, src/main/java/org/omoknoone/ppm/domain/schedule/dto/UpdateTableDataDTO.java, src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRepository.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
- #60
- updateGauge
- updatePie
- updateTable
>
=> [PR] 대시보드 그래프 데이터 update에 필요한 data 조회 기능 개발-1

src/main/java/org/omoknoone/ppm/domain/schedule/aggregate/ScheduleRequirementMap.java, src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleRequirementMapController.java, src/main/java/org/omoknoone/ppm/domain/schedule/dto/CreateScheduleRequirementMapDTO.java, src/main/java/org/omoknoone/ppm/domain/schedule/dto/RequestCreateScheduleRequirementMapDTO.java, src/main/java/org/omoknoone/ppm/domain/schedule/dto/ScheduleRequirementMapDTO.java, src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRequirementMapRepository.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleRequirementMapService.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleRequirementMapServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/schedule/vo/ResponseScheduleHistory.java, src/main/java/org/omoknoone/ppm/domain/schedule/vo/ResponseScheduleRequirementMap.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersServiceImpl.java
- #32
- 일정 요구사항 등록 기능
- 일정 요구사항 삭제 기능
- 일정에 따른 요구사항 조회 기능
[fix] 이해관계자 어노테이션 오류 수정 
[fix] ResponseScheduleHistory 코드 비어있는 오류 수정
포함되어있습니다.
=> [PR] 일정 요구사항 맵 기능 구현

src/main/java/org/omoknoone/ppm/config/RestTemplateConfig.java, src/main/java/org/omoknoone/ppm/domain/holiday/HolidayControllerTest.java, src/main/java/org/omoknoone/ppm/domain/holiday/aggregate/Holiday.java, src/main/java/org/omoknoone/ppm/domain/holiday/dto/CreateHolidayDTO.java, src/main/java/org/omoknoone/ppm/domain/holiday/dto/HolidayDTO.java, src/main/java/org/omoknoone/ppm/domain/holiday/repository/HolidayRepository.java, src/main/java/org/omoknoone/ppm/domain/holiday/service/HolidayService.java, src/main/java/org/omoknoone/ppm/domain/holiday/service/HolidayServiceImpl.java
#12 
- 호출 시점의 달의 휴일 데이터를 가져와, DB holiday에 저장하는 메소드(testCode)
- 입력한 년도의 휴일 데이터를 가져와 DB holiday에 저장하는 메소드(yearCode)
- 실제 서비스 베포전에는 Controller를 없애고 Service만 수정하여 Scheduling할 계획. 
- ("Scheduled(cron = "0 0 0 1 * *")" 어노테이션 사용 예정. 갱신 시점이나 범위에 대해서 _**코멘트 부탁드립니다.**_)
- 공공데이터 API로 부터 호출하여 사용. 그러나 약 5분 간격으로 사용할 수 있기에 이를 조심해야함.(아마 API 서비스 자체적인 이유로 추측)
- 사용되는 서비스키에 대해선 slack 참고
=> [PR} 휴일 추가 기능

src/main/java/org/omoknoone/ppm/domain/project/aggregate/Project.java, src/main/java/org/omoknoone/ppm/domain/project/aggregate/ProjectHistory.java, src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectController.java, src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectHistoryController.java, src/main/java/org/omoknoone/ppm/domain/project/dto/ModifyProjectHistoryDTO.java, src/main/java/org/omoknoone/ppm/domain/project/dto/ModifyProjectRequestDTO.java, src/main/java/org/omoknoone/ppm/domain/project/dto/ProjectHistoryDTO.java, src/main/java/org/omoknoone/ppm/domain/project/repository/ProjectHistoryRepository.java, src/main/java/org/omoknoone/ppm/domain/project/service/ProjectHistoryService.java, src/main/java/org/omoknoone/ppm/domain/project/service/ProjectHistoryServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/project/service/ProjectService.java, src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/project/vo/ResponseProjectHistory.java
> - #42 
> 프로젝트 수정 및 프로젝트 수정 시 project_history에 수정 내역 저장 기능 구현, 수정 내역 조회 기능 구현
>
=> [PR] 프로젝트 수정, 수정 내역 기록, 수정 내역 조회 기능 구현

src/main/java/org/omoknoone/ppm/domain/employee/controller/EmployeeController.java, src/main/java/org/omoknoone/ppm/domain/employee/dto/ModifyPasswordRequestDTO.java, src/main/java/org/omoknoone/ppm/domain/employee/exception/PasswordMismatchException.java, src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeService.java, src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceImpl.java
- #16 
- 새로 바뀐 비밀번호와 확인용 비밀번호를 비교 검증
- 같지 않을 시 예외(`PasswordMismatchException`) 발생
- 새로 바뀐 비밀번호도 암호화 되어 저장
> URL을 Restful하게 작성하고 싶어 EmployeeId는 `@PathVariable`로 받고 다른 정보들은 DTO로 전달 받아봤습니다
=> [PR] 비밀번호 수정 기능 개발

src/main/resources/logback.xml
- #11 
> Logback을 사용하여 log를 파일로 저장
> 파일 경로는 ./logs/logback-현재날짜_{인덱스번호}.log로 저장
> `.yml`로는 지원을 하지 않는 기능이 있어 `.xml`로 파일 설정 저장
=> [PR] Log 파일로 저장하기

src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleController.java, src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRepository.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
> - #37 
> 
- startDate와 endDate를 입력 받아 그 사이에 해당하는 일정 목록을 조회하는 기능 구현
=> [PR] 날짜 설정 범위에 따른 일정목록 조회(필터링) 기능 구현

src/main/java/org/omoknoone/ppm/domain/project/aggregate/Project.java, src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectController.java, src/main/java/org/omoknoone/ppm/domain/project/dto/ModifyProjectHistoryDTO.java, src/main/java/org/omoknoone/ppm/domain/project/dto/ModifyProjectRequestDTO.java, src/main/java/org/omoknoone/ppm/domain/project/service/ProjectService.java, src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/schedule/aggregate/Schedule.java, src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRepository.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
- #39 
> 프로젝트 복사 시 일정, 프로젝트의 형태만 복사
> 복사할 프로젝트의 일정 조회 시 삭제 되지 않은 일정만을 조회해야하므로 Repository 수정
=> [PR] 프로젝트 복사 기능 구현

src/main/java/org/omoknoone/ppm/domain/employee/aggregate/Employee.java, src/main/java/org/omoknoone/ppm/domain/employee/controller/EmployeeController.java, src/main/java/org/omoknoone/ppm/domain/employee/dto/ViewEmployeeResponseDTO.java, src/main/java/org/omoknoone/ppm/domain/employee/repository/EmployeeRepository.java, src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeService.java, src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceImpl.java
> - #39 
> 
- employeeName을 통한 사원 검색 기능 구현
=> [PR] employeeName을 통한 사원 검색 기능 구현

src/main/java/org/omoknoone/ppm/domain/employee/controller/EmployeeController.java, src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectController.java
=> [PR]코드오류수정

src/main/java/org/omoknoone/ppm/common/annotation/NoLogIfDraft.java, src/main/java/org/omoknoone/ppm/common/aop/EntityModificationAspect.java, src/main/java/org/omoknoone/ppm/common/enums/RecordingTarget.java, src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMemberHistory.java, src/main/java/org/omoknoone/ppm/domain/projectmember/controller/ProjectMemberController.java, src/main/java/org/omoknoone/ppm/domain/projectmember/dto/ModifyProjectMemberRequestDTO.java, src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberHistoryRepository.java, src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberHistoryService.java, src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberHistoryServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java, src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsController.java, src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsHistoryController.java, src/main/java/org/omoknoone/ppm/domain/requirements/dto/ModifyRequirementRequestDTO.java, src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsHistoryService.java, src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsHistoryServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsService.java, src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleController.java, src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleHistoryController.java, src/main/java/org/omoknoone/ppm/domain/schedule/dto/RequestModifyScheduleDTO.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleHistoryService.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleHistoryServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
- #116 
- #47
- #41
> 구성원, 프로젝트, 일정, 요구사항의 수정/삭제 시 수정내역 관리를 합니다.
> `@어노테이션` 형태로 개발하려고 했으나 개발 일정에 맞춰 추후 고도화 하기로 하였으며 메소드 형태로 개발하였음
=> [PR] 수정내역 관리 기능 개발

src/main/java/org/omoknoone/ppm/domain/employee/aggregate/Employee.java, src/main/java/org/omoknoone/ppm/domain/employee/repository/EmployeeRepository.java, src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeService.java, src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectController.java, src/main/java/org/omoknoone/ppm/domain/project/dto/CreateProjectRequestDTO.java, src/main/java/org/omoknoone/ppm/domain/project/service/ProjectService.java, src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/aggregate/Graph.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/aggregate/ProjectDashboard.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/controller/GraphController.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/dto/GraphDTO.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/repository/GraphRepository.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphService.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/ProjectDashboardService.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/ProjectDashboardServiceImpl.java
- #60 
- #25 
> projectId를 통해 대시보드에 사용될 graph init하는 기능 구현
line graph에 필요한 data들을 update하는 기능 구현 : 현재 날짜를 기준으로 해당하는 날짜의 인덱스에 전체 진행률 값을 업데이트 합니다.
> 코드가 많이 지저분합니다 특히 projectId와 같은 값들 String으로 되어있어 Integer, Long 으로 추후에 통일하는 리팩토링 필요할 것 같습니다
=> [PR] 대시보드 그래프 init 및 line graph update 기능 구현

src/main/java/org/omoknoone/ppm/config/WebConfig.java, src/main/java/org/omoknoone/ppm/security/CorsConfig.java
> Vue프로젝트 CORS 충돌 해결
> Vue 포트는 8887
=> [PR] [hotfix] Vue프로젝트 CORS 충돌 해결

src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphService.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
> - #60
> 대시보드 그래프 관련 수정 사항이 있어 수정하였습니다 
> 1. 그래프 초기화 시 프로젝트의 시작날짜, 끝날짜만 입력되도록 되어 있어서 10등분한 날짜 모두 채워지도록 수정
> 2. test용으로 리터럴값으로 채워져있던 부분 스케쥴 서비스에서 받아오도록 수정 
>
=> [PR] graph update 부분 수정 

src/main/java/org/omoknoone/ppm/domain/project/repository/ProjectRepository.java, src/main/java/org/omoknoone/ppm/domain/project/service/ProjectService.java, src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphScheduler.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphService.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java
>- #60 
> 상태가 착수인 프로젝트들의 그래프 데이터를 매일 오후 12시에 업데이트 합니다
=> [PR] 매일 오후 12시에 상태가 착수인 프로젝트들의 그래프 데이터 업데이트

src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsController.java, src/main/java/org/omoknoone/ppm/domain/requirements/dto/RequirementsListByProjectDTO.java, src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleController.java, src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRepository.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceCalculator.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
> - #130 
> 
- 차주에 끝나야할 일정조회 기능 구현
- 금주 및 차주의 일정을 활용한 각각의 완료 일정 비율 계산 기능 구현
=> [PR] 차주에 끝나야할 일정조회 및 금주, 차주 완료 일정 비율 계산 기능

src/main/java/org/omoknoone/ppm/domain/project/aggregate/Project.java, src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectController.java, src/main/java/org/omoknoone/ppm/domain/project/service/ProjectService.java, src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/project/vo/ProjectModificationResult.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/aop/GraphAspect.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphService.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java
> 1. 예상진행률 관련한 로직 수정
> 2. 프로젝트 날짜가 수정되었을 경우 라인 그래프의 데이터도 업데이트 되도록 함 (날짜 이외의 항목에서 수정이 일어나면 업데이트 하지 않음)
> 3. 프로젝트 수정 시 RequestBody에 입력하지 않은 값은 0 또는 null로 전달되어 기존의 값에 덮어씌워지는 현상 방지
> 컨트롤러 부분에서 conflict 수정 예정 
> line update 부분 int[] expectProgress 부분은 추후 메소드로 변경 예정
=> [PR] 그래프 관련 로직 수정

src/main/java/org/omoknoone/ppm/domain/project/repository/ProjectRepository.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphService.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/schedule/dto/UpdateDataDTO.java
> 1. Gauge Graph의 데이터 업데이트 방식이 front와 달랐던 문제 해결 (리터럴 값 하나가 아닌 한 칸짜리 배열 안에 data 하나가 있어야 함)
> 2. 프로젝트 수정 시 값이 null일 경우 0으로 반환
> 3. graph update시 null error 방지 코드 작성
=> [PR] Gauge Graph 데이터 업데이트 형식 수정

src/main/java/org/omoknoone/ppm/domain/project/controller/ProjectController.java, src/main/java/org/omoknoone/ppm/domain/project/dto/ViewProjectResponseDTO.java, src/main/java/org/omoknoone/ppm/domain/project/repository/ProjectRepository.java, src/main/java/org/omoknoone/ppm/domain/project/service/ProjectService.java, src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java, src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java, src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java, src/test/resources/ProjectTest.http
- #135 
- 프로젝트 목록 및 상세 조회 기능 개발
=> [PR] 프로젝트 목록 및 상세 조회 기능 개발

src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsController.java, src/main/java/org/omoknoone/ppm/domain/requirements/repository/RequirementsRepository.java, src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsService.java, src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
> - #133 
> 
- 프로젝트의 startDate와 endDate를 기준으로 10등분 된 날짜 조회기능은 잘 됐으나 그에 맞는 비율이 일치되게 나오지 않아 일치되도록 수정하였습니다.
- 요구사항 쪽 프론트 작업을 하면서 요구사항이 삭제되었을 때는 요구사항 List에는 조회되지 않도록 하기 위해 코드를 일부 수정하였습니다.
=> [PR] 구간별 누적 비율 계산 코드 수정 및 요구사항 관련 코드 수정

src/main/java/org/omoknoone/ppm/domain/project/repository/ProjectRepository.java, src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
- #135
> 프로젝트 목록 조회시 ID 기준으로 내림차순으로 조회
>
=> [PR] 프로젝트 목록 ID 기준으로 내림차순

src/main/java/org/omoknoone/ppm/domain/projectDashboard/controller/GraphController.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphService.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java
> - #143
> 그래프 삭제 기능이 추가되었습니다.
> 추후 프로젝트 삭제 시 그래프 데이터도 함께 삭제되도록 AOP추가 예정입니다.
=> [PR] Graph Delete기능 구현

src/main/java/org/omoknoone/ppm/domain/employee/aggregate/Employee.java, src/main/java/org/omoknoone/ppm/domain/employee/dto/SignUpEmployeeRequestDTO.java, src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/permission/controller/PermissionController.java, src/main/java/org/omoknoone/ppm/domain/permission/dto/RequestCreatePermissionDTO.java, src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMember.java, src/main/java/org/omoknoone/ppm/domain/projectmember/dto/CreateProjectMemberRequestDTO.java, src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java, src/test/resources/api/tests/EmployeeTest.http, src/test/resources/api/tests/NotificationTest.http, src/test/resources/api/tests/PermissionTest.http, src/test/resources/api/tests/ProjectMemberTest.http, src/test/resources/api/tests/ProjectTest.http, src/test/resources/api/tests/ProjectdashboardTest.http, src/test/resources/api/tests/RequirementsTest.http, src/test/resources/api/tests/ScheduleTest.http, src/test/resources/api/tests/StakeholdersTest.http, src/test/resources/api/tests/TaskTest.http
> - #142 
> 1. 컨트롤러 별로 .http파일을 추가하여 Postman을 대체하고 api test를 공유할 수 있습니다.
> 2. String형으로 되어있는 날짜 데이터들을 LocalDate형으로 일부 수정하였습니다.
> 3. DeleteMapping에 해당하는 컨트롤러의 반환형이  NO_CONTENT인 부분들을 .ok() 로 통일하였습니다.
> notification및 projectMember는 추후 수정
=> [PR] .http파일 추가 및 코드 수정사항

.gitignore, Dockerfile
> main branch에 Dockerfile을 추가하게 해주십시오 🥺
=> [PR] Dockerfile 추가 

Dockerfile, build.gradle, src/main/java/org/omoknoone/ppm/config/JasyptConfig.java, src/main/java/org/omoknoone/ppm/projectDashboard/controller/ProjectDashboardController.java, src/main/java/org/omoknoone/ppm/projectDashboard/service/ProjectDashboardServiceImpl.java, src/main/resources/application.yml
=> [PR] jasypt추가 

src/main/java/org/omoknoone/ppm/domain/employee/dto/SignUpEmployeeRequestDTO.java, src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeService.java, src/main/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMember.java, src/main/java/org/omoknoone/ppm/domain/projectmember/dto/CreateProjectMemberRequestDTO.java, src/test/java/org/omoknoone/ppm/domain/employee/service/AuthServiceTest.java, src/test/java/org/omoknoone/ppm/domain/employee/service/EmployeeServiceTests.java
- #150 
> 회원 Domain에 있는 Service의 테스트 코드 작성
> 사용하지 않는 메소드는 주석 처리 하였습니다
> 테스트 코드 일단 간단하게 작성하였습니다.
> 주석처리한 메소드는 사용할 것인지 확인 부탁드려요~ @orlzlL
=> [PR] 회원(Auth, Employee) 관련 테스트 코드 작성

src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
- scheduleServiceImpl 생성자에 commonCodeRepository가 빠져있는 오류 해결
>
=> [PR] Hotfix/schedule sheetdata merge error resolve

src/main/java/org/omoknoone/ppm/domain/project/dto/CreateProjectRequestDTO.java, src/main/java/org/omoknoone/ppm/domain/project/dto/ModifyProjectHistoryDTO.java, src/test/java/org/omoknoone/ppm/domain/project/service/ProjectServiceTest.java
- #154 
> 프로젝트의 서비스 영역 테스트 코드 작성
테스트 코드에 필요한 DTO `@Setter`추가
>
=> [PR] 프로젝트(Project) 테스트 코드 작성

src/main/java/org/omoknoone/ppm/domain/schedule/aggregate/Schedule.java, src/main/java/org/omoknoone/ppm/domain/schedule/dto/RequestModifyScheduleDTO.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java, src/test/java/org/omoknoone/ppm/domain/schedule/service/ScheduleHistoryServiceTests.java, src/test/java/org/omoknoone/ppm/domain/schedule/service/ScheduleRequirementMapServiceTest.java, src/test/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceTests.java
- #157 
> 일정 도메인의 `Schedule`, `ScheduleHistory`, `ScheduleRequirementsMap` Service 테스트 코드 작성
`ScheduleServiceCalculator`는 아직 구현 중이라 테스트 코드 미작성
`@Disabled` 되어있는 테스트 코드는 현재 수정 중이거나 오류가 있는 테스트 코드 (수정 필)
=> [PR] 일정 도메인 테스트 코드 작성

src/main/java/org/omoknoone/ppm/domain/requirements/dto/ModifyRequirementRequestDTO.java, src/main/java/org/omoknoone/ppm/domain/requirements/dto/RequirementsHistoryDTO.java, src/test/java/org/omoknoone/ppm/domain/requirements/service/RequirementsHistoryServiceTests.java, src/test/java/org/omoknoone/ppm/domain/requirements/service/RequirementsServiceTests.java
- #160 
> 요구사항 도메인의 `Requirement` , `RequirementHistory` 서비스 영역 테스트 코드 작성
테스트 코드 작성에 필요한 DTO에 Setter와 변수 추가
>
=> [PR] 요구사항 도메인의 서비스 테스트 코드 작성

src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMember.java, src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleController.java, src/main/java/org/omoknoone/ppm/domain/schedule/dto/RequestCreateScheduleRequirementMapDTO.java, src/main/java/org/omoknoone/ppm/domain/task/controller/TaskController.java
ProjectMemberCreatedDate 데이터 형 변환 및 TODO 추가
>
=> [fix] ProjectMemberCreatedDate 데이터 형 변환 및 TODO 추가

src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleHistoryController.java, src/main/java/org/omoknoone/ppm/domain/schedule/dto/ViewScheduleHistoryDTO.java, src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleHistoryRepository.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleHistoryService.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleHistoryServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/schedule/vo/ResponseViewScheduleHistory.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/controller/StakeholdersController.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/dto/ViewStakeholdersDTO.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/repository/StakeholdersRepository.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersService.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/vo/ResponseViewStakeholders.java, src/test/java/org/omoknoone/ppm/domain/schedule/service/ScheduleHistoryServiceTests.java
[feat] 일정 이해관계자 조회 시, 사원번호, 이름, 역할 조회 기능 구현
[feat] 일정 수정내역 조회 시, 이름, 사원번호, 역할 조회 기능
>
=> [PR] 일정 이해관계자, 수정내역 조회 시, 이름, 사원번호, 역할 조회 기능 구현

src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/permission/repository/PermissionRepository.java, src/main/java/org/omoknoone/ppm/domain/permission/service/PermissionServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/projectmember/controller/ProjectMemberController.java, src/main/java/org/omoknoone/ppm/domain/projectmember/dto/ProjectMemberDTO.java, src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java, src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java, src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/repository/StakeholdersRepository.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersServiceImpl.java
최근 작업 파일 병합 후, 생긴 오류를 해결한 브랜치입니다.
- repository의  List<ProjectMember> findByProjectMemberProjectId(Integer projectId); 를   List<ProjectMember> findProjectMembersByProjectMemberProjectId(Integer projectId); 로 수정
- JQPL이 아닌 JPA 활용
- 이에 따라 연관 항목의 호출명도 수정(NotificationServiceImpl, ProjectMemberService, ProjectMemberServiceImpl)
- ProjectMemberServiceImpl 의 viewProjectMembersByProject 의 반환형 수정 및 내부 코드 변경
- 이에 따라 연관 항목의 호출명 및 반환형도 수정(ProjectMemberService, GraphServiceImpl, ProjectMemberController,
- NotificationServiceImpl에서 stakeholdersServiceImpl.findByScheduleId 반환형 수정
- Stakeholders ServiceImpl 리스트 반환형 수정
- 중괄호 오류 수정
>
=> [PR] 병합 후, 오류 수정 PR

src/main/java/org/omoknoone/ppm/domain/projectmember/controller/ProjectMemberController.java, src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java, src/test/resources/api/tests/ProjectMemberTest.http
- #142 
> 일부 소스 코드의 오타를 발견하여 수정 하고 http 테스트를 위한 예시를 추가했습니다.
=> [PR] 프로젝트 구성원 http 테스트 셋업

src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java, src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/dto/RoleAndScheduleIdList.java
- #173 
- #172 
- #171
- 병합 후, 실행오류 해결
- 반환형, 데이터 타입 수정
- **권한 삭제에 따른 시트 조회 기능 수정**
- **Permission을 통한 필터링 작업 -> ProjectMember와 Stakeholders를 통한 필터링 작업**
>
=> [PR] 병합 후, 오류 수정 및 일정 시트 조회 기능 수정

src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/permission/service/PermissionService.java, src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersService.java
> serviceImpl 주입받는 것을 service로 변경
=> [fix] 잘못된 코드 해결

src/main/java/org/omoknoone/ppm/domain/projectmember/dto/ViewProjectMembersByProjectResponseDTO.java, src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java, src/test/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceTests.java
=> [PR] 조회, 생성, 수정 부분 오류 및 클라이언트에 보여줘야 하는 값으로 변경

src/main/java/org/omoknoone/ppm/domain/schedule/controller/ScheduleController.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
calculateScheduleRatios 메소드에서 기존에 startDate와 endDate를 받아오던 것을 projectId 값을 받아오도록 수정
=> [PR] calculateScheduleRatios 메소드 projectId 값을 받아오도록 수정

src/main/java/org/omoknoone/ppm/domain/schedule/repository/ScheduleRepository.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
> 구간별 예상 진행률 계산 시 projectId 반영되도록 수정
=> [PR] 구간별 예상 진행률 계산 시 projectId 반영되도록 수정

src/main/java/org/omoknoone/ppm/domain/notification/aggregate/entity/Notification.java, src/main/java/org/omoknoone/ppm/domain/notification/controller/NotificationController.java, src/main/java/org/omoknoone/ppm/domain/notification/dto/NotificationResponseDTO.java, src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationService.java, src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceImpl.java, src/test/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceTest.java
> MariaDB에서 read가 예약어로 활용 되어 markAsRead로 일괄 수정, db의 필드명도 변경될 예정입니다.
=> [PR] notificadtion 코드 수정 MariaDB에서 read가 예약어로 활용 되어 markAsRead로 일괄 수정

src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
> 데이터 형식에 맞추어 값을 가져오는 부분들을 수정하였습니다
>
=> [PR] 그래프 데이터 관련 수정

src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java, src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java, src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java, src/main/java/org/omoknoone/ppm/security/AuthenticationFilter.java, src/main/java/org/omoknoone/ppm/security/CorsConfig.java, src/main/java/org/omoknoone/ppm/security/WebSecurity.java
=> [PR] 로그인 성공 시, header에 정보 추가

src/main/java/org/omoknoone/ppm/domain/notification/controller/NotificationController.java, src/main/java/org/omoknoone/ppm/domain/notification/repository/NotificationRepository.java, src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationScheduler.java, src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationService.java, src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberService.java, src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleServiceImpl.java
> 
- PM, PL 권한을 가진 사람들에게만 알림이 가도록 설정
- 알림 삭제 기능 개발
- is_deleted가 false인 notification만 조회되도록 수정
>
=> [PR] 변경된 DB에 맞게 알림 코드 수정, 알림 삭제 기능 구현

src/main/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceImpl.java
올바른 index를 반환하지 않아 로직 수정함
> 라인 그래프 현재 진행률 업데이트 하는 부분에서 올바른 index값이 반환되지 않아 로직을 수정했습니다
>
=> [PR] line graph update 로직 수정

src/main/java/org/omoknoone/ppm/domain/notification/repository/NotificationRepository.java, src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceImpl.java
>
- Notification 화면에 employee가 가진 모든 알림이 출력되던 부분을 최신 10개의 알림만 나오도록 코드 수정
=> [PR] 최신 10개의 알림만 화면에 나오도록 코드 수정

src/test/java/org/omoknoone/ppm/domain/commoncode/service/CommonCodeServiceTest.java, src/test/java/org/omoknoone/ppm/domain/holiday/service/HolidayServiceTest.java, src/test/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceTest.java, src/test/java/org/omoknoone/ppm/domain/notification/service/NotificationSettingsServiceTest.java, src/test/java/org/omoknoone/ppm/domain/notification/service/SentServiceTest.java, src/test/java/org/omoknoone/ppm/domain/project/service/ProjectHistoryServiceTest.java, src/test/java/org/omoknoone/ppm/domain/projectDashboard/service/GraphServiceTest.java, src/test/java/org/omoknoone/ppm/domain/projectDashboard/service/ProjectDashboardServiceTest.java, src/test/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberHistoryServiceTest.java, src/test/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceTest.java, src/test/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersServiceTest.java, src/test/java/org/omoknoone/ppm/domain/task/service/TaskServiceTest.java
>
- 각각의 Service에 대해서 testCode 작성
>
=> [PR] testCode 작성

src/main/java/org/omoknoone/ppm/domain/task/dto/ModifyTaskDTO.java, src/test/java/org/omoknoone/ppm/domain/holiday/service/HolidayServiceTest.java, src/test/java/org/omoknoone/ppm/domain/projectdashboard/service/GraphServiceTest.java, src/test/java/org/omoknoone/ppm/domain/projectdashboard/service/ProjectDashboardServiceTest.java
- ModifyTaskDTO에 Setter 추가
- #201 
- Holiday, Graph, ProjectDashboard
- ModifyTaskDTO setter 추가
>
=> [Hotfix] Test 오류 임시 수정

src/main/java/org/omoknoone/ppm/config/WebConfig.java, src/main/java/org/omoknoone/ppm/security/CorsConfig.java
=> [HotFix] CORS 추가

src/main/java/org/omoknoone/ppm/config/WebConfig.java, src/main/java/org/omoknoone/ppm/security/CorsConfig.java
=> [fix] CORS에 WWW추가

src/main/java/org/omoknoone/ppm/domain/project/service/ProjectServiceImpl.java
- #208 
> 프로젝트 목록 조회 isDeleted 처리 확인
>
=> [PR] 프로젝트 목록 조회 시 isDeleted 추가

src/main/java/org/omoknoone/ppm/domain/notification/controller/NotificationController.java
> - notificationController 수정
>
=> [PR] notificationController 수정

src/main/java/org/omoknoone/ppm/domain/notification/service/CheckNotificationServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationScheduler.java, src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/notification/service/strategy/EmailNotificationStrategy.java, src/main/java/org/omoknoone/ppm/domain/schedule/dto/FindSchedulesForWeekDTO.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/repository/StakeholdersRepository.java
> - #209 
> 
- ProjectMember가 PA 권한을 가지고 있을 때 완료되지 않은 일정에 대하여 ProjectMember가 담당자 역할을 가지고 있는 일정만 매일 오전 9시에 알림을 받는 기능 구현
=> [PR] 이해관계자 중 담당자에 따른 알림 생성 기능 구현

src/main/java/org/omoknoone/ppm/domain/notification/aggregate/entity/NotificationSettings.java, src/main/java/org/omoknoone/ppm/domain/notification/service/NotificationServiceImpl.java
> 
- NotificationTemplate 수정
- Notification Entity Email_enabled, Slace_enabled default 값 false -> true 로 수정
=> [PR] NotificationTemplate 수정

src/main/java/org/omoknoone/ppm/domain/employee/aggregate/Employee.java
=> [Release] PPM Back v.1.1.1

src/main/java/org/omoknoone/ppm/PpmApplication.java, src/main/java/org/omoknoone/ppm/config/TimeZoneConfig.java
- #226
> ec2에서 서버를 실행하면 한국 시간으로 설정되어 있지 않아 Timezone 설정을 추가
> local 환경에서는 잘 되는데 잘 작동하는 지는 ec2에 배포 해봐야 알 것 같네요
=> [PR] 서버 시간 한국시간으로 설정하기

src/main/java/org/omoknoone/ppm/domain/employee/aggregate/Employee.java
- #226
- #227
> 서버 시간 한국으로 변경
>
=> [Release] PPM Back v.1.1.2

src/main/java/org/omoknoone/ppm/PpmApplication.java, src/main/java/org/omoknoone/ppm/domain/employee/repository/EmployeeRepository.java, src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMember.java, src/main/java/org/omoknoone/ppm/domain/projectmember/aggregate/ProjectMemberHistory.java, src/main/java/org/omoknoone/ppm/domain/projectmember/repository/ProjectMemberRepository.java, src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberHistoryService.java, src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberHistoryServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/projectmember/service/ProjectMemberServiceImpl.java
- #235 
> projectMember의 기능 수정 및 일부 코드 정리
- ProjectMember aggregate에서 JoinColumn을 대신 Column으로 변경하였습니다.
- EmployeeRepository의 jpql의 쿼리문을 일부 수정 하였습니다.
- 일부 기존 코드의 위치 조정과 Import문에서 사용 되지 않는 코드들을 정리하였습니다.
>
>
=> [refactor] 프로젝트 구성원 기능 일부 개선 및 aggregate 수정

src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsController.java, src/main/java/org/omoknoone/ppm/domain/requirements/controller/RequirementsHistoryController.java, src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsService.java, src/main/java/org/omoknoone/ppm/domain/requirements/service/RequirementsServiceImpl.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleRequirementMapService.java, src/main/java/org/omoknoone/ppm/domain/schedule/service/ScheduleService.java, src/main/java/org/omoknoone/ppm/domain/stakeholders/service/StakeholdersService.java, src/main/java/org/omoknoone/ppm/domain/task/service/TaskService.java
- #231
- 요구사항에서 Entity로 작성된 부분을 DTO로 변경
- 추가로 작업해야하는 부분은 TODO로 표기
기존에 Entity를 단순히 DTO로만 변경하려고 했던 부분 계획 변경해야할 것 같습니다.
DTO도 정리가 필요할 것으로 보아 DTO뿐 아니라 코드의 구현부 하나하나 메소드별로 하나씩 고쳐나가려고 합니다.
>
=> [Refactor] 요구사항에서 Entity로 작성된 부분을 DTO로 변경
